### ISSUE TITLE
Application Architecture starting point

### ISSUE THREAD

**Issue by Jenniferstrej** [libero/community#5]
From the [Initial discussions](https://github.com/libero/community/issues/4) Issue we suggested an ideal general software architecture requirements. What I don't see defined yet is our components architecture starting point. How do we plan our components and process to look like, workflows, dashboard, publication process? I believe we have eLife's process as a starting point, but being flexible about it. I would suggest publishing a starting software architecture diagram which would contain a smaller set of applications that will support an initial version of Libero.

**Comment by giorgiosironi** [comment]
@thewilkybarkid had some high-level draft of that which should eventually be prototyped in https://github.com/libero/walking-skeleton

**Comment by giorgiosironi** [comment]
The README in https://github.com/libero/walking-skeleton now has an architectural diagram showing a set of key services.
